config/routes.rb
Rails.application.routes.draw do
  root to: "users#index"

  resources :professions
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profession.rb
class Profession < ApplicationRecord
  validates_presence_of :name, :rating

  has_many :profestions_users
  has_many :users, through: :profestions_users
end

app/models/profession_user.rb
class ProfessionUser < ApplicationRecord
  belongs_to :user
  belongs_to :profession
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :email

  has_many :profestions_users
  has_many :profestions, through: :profestions_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/professions_controller.rb
class ProfessionsController < ApplicationController
  before_action :set_profession, only: %i[ show edit update destroy ]

  # GET /professions or /professions.json
  def index
    @professions = Profession.all
  end

  # GET /professions/1 or /professions/1.json
  def show
  end

  # GET /professions/new
  def new
    @profession = Profession.new
  end

  # GET /professions/1/edit
  def edit
  end

  # POST /professions or /professions.json
  def create
    @profession = Profession.new(profession_params)

    respond_to do |format|
      if @profession.save
        format.html { redirect_to @profession, notice: "Profession was successfully created." }
        format.json { render :show, status: :created, location: @profession }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profession.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professions/1 or /professions/1.json
  def update
    respond_to do |format|
      if @profession.update(profession_params)
        format.html { redirect_to @profession, notice: "Profession was successfully updated." }
        format.json { render :show, status: :ok, location: @profession }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profession.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professions/1 or /professions/1.json
  def destroy
    @profession.destroy
    respond_to do |format|
      format.html { redirect_to professions_url, notice: "Profession was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_profession
    @profession = Profession.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def profession_params
    params.require(:profession).permit(:name, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:email, :experience)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OksiCourseworkDoneByOstap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/professions/_form.html.erb
<%= form_with(model: profession) do |form| %>
  <% if profession.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profession.errors.count, "error") %> prohibited this profession from being saved:</h2>

      <ul>
        <% profession.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, "Name" %>
    <%= form.text_field :name, id: 'name', required: true %>
  </div>
  <br>

  <div>
    <%= form.label :rating, "Rating" %>
    <%= form.number_field :rating, id: 'rating' %>
  </div>
  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/professions/edit.html.erb
<h1>Editing Profession</h1>

<%= render 'form', profession: @profession %>

<%= link_to 'Show', @profession %> |
<%= link_to 'Back', professions_path %>

app/views/professions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Professions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rating</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @professions.each do |profession| %>
      <tr>
        <td><%= profession.name %>
        <td><%= profession.rating %>
        <td><%= link_to 'Show', profession %></td>
        <td><%= link_to 'Edit', edit_profession_path(profession) %></td>
        <td><%= link_to 'Destroy', profession, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profession', new_profession_path %>
<hr>
<%= link_to 'Users', users_path %>

app/views/professions/new.html.erb
<h1>New Profession</h1>

<%= render 'form', profession: @profession %>

<%= link_to 'Back', professions_path %>

app/views/professions/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  Profession: <%= @profession.name %>
</h2>
<h3> Rating: <%= @profession.rating %></h5>
<h3> Created At: <%= @profession.created_at.to_formatted_s(:long_ordinal) %></h6>

<%= link_to 'Edit', edit_profession_path(@profession) %> |
<%= link_to 'Back', professions_path %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, "E-mail" %>
    <%= form.text_field :email, id: 'email', required: true %>
  </div>
  <br>

  <div>
    <%= form.label :experience, "Experience" %>
    <%= form.number_field :experience, id: 'experience' %>
  </div>
  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Experience</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.experience %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<hr>
<%= link_to 'Professions', professions_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  User: <%= @user.email %>
</h2>
<h3> Experience: <%= @user.experience %></h5>
<h3> Created At: <%= @user.created_at.to_formatted_s(:long_ordinal) %></h6>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>